### ISSUE TITLE
"Clear Scene" retains previous file in memory

### ISSUE THREAD

**Issue by frank26080115** [flux3dp/beam-studio#8]
v1.3.4-beta Windows x64

If I load a SVG file, then use "clear scene", then load another SVG file, the first SVG file's contents is loaded instead of the second SVG file's contents. (the second file's layers are listed though)

I've uploaded a video illustrating the problem. (inside the ZIP)
[clearscenebug.zip](https://github.com/flux3dp/beam-studio/files/4937120/clearscenebug.zip)

**Comment by dkdkwizard** [comment]
Hi @frank26080115 ,

Thank you for reporting the bug.

I have followed the same process, but failed to reproduced the bug. The second SVG file was loaded as expected.
Does this happen to you every time?
Also, there might be some bug when parsing your SVG files which causes this bug.
Could you kindly provide SVG files in the video so that I can test if there is any bugs when loading your SVG files.

Thanks.

**Comment by frank26080115** [comment]
[clear_scene_bug.zip](https://github.com/flux3dp/beam-studio/files/4955931/clear_scene_bug.zip)

I have attached all the files here

Yes it happens every time

**Comment by dkdkwizard** [comment]
Hi @frank26080115 ,

Thank you for providing the files. I have found that there is a bug when clearing scene, Beam Studio would not clear the references of imported SVGs in v1.3.4 beta.
We will fix this bug in next beta version.
For now, you can use ctrl + R to reload app when you need to clear scene. This will clear SVG references as well.

Thank you again for reporting this bug.

**Comment by dkdkwizard** [comment]
Hi @frank26080115 ,

We have built Beam Studio v1.4.0 beta, and this bug should be fixed.

Kindly update to Beam Studio v1.4.0 and see if this bug still occurs.
Thank you.
